### ISSUE TITLE
When pushing app to device, app icon doesn't appear until phone rebooted

### ISSUE THREAD

**Issue by benfrancis** [mozilla/r2d2b2g#452]
Reproduced with Firefox OS Simulator 3.0 preview 6(?) and a Geeksphone Keon.

Reproduced by several people at Madrid app workshop.

CC @Rik

**Comment by rpl** [comment]
seems like bugzilla 842725 (https://bugzilla.mozilla.org/show_bug.cgi?id=842725)
probably is not yet included in the b2g version installed on the Geeksphone Keon stock ROM.

Could you get from that phone the following data?
- Settings -> Device Information -> Software
- Settings -> Device Information -> More Information:
  - Platform Version
  - Build Identifier

**Comment by mykmelez** [comment]
It would also be useful to know if you saw this with both hosted and packaged apps or only with packaged ones, since the bug that @rpl references was specific to packaged apps.

Boy, I sure hope those phones have newer ROMs. Although I also hope this problem turns out to be that bug, since the fix is then to update the phone, which hopefully is simple enough.

**Comment by nickdesaulniers** [comment]
@rpl is right: the geeksphones are running 1.0.1.  The unagis running 1.1.0 do not have this problem.  At least now the geeksphones are receiving updates, but they only update to the latest 1.0.1, not 1.1.0.

**Comment by nickdesaulniers** [comment]
@benfrancis , now that geeksphones are receiving updates... can you update your device and reopen this, if it is still a problem?

**Comment by mykmelez** [comment]
If the geeksphones are going to be on 1.0.1 for a while, then perhaps we should revisit the decision not to land the fix for [bug 842725](https://bugzilla.mozilla.org/show_bug.cgi?id=842725) on that branch. cc: @fabricedesre

**Comment by benfrancis** [comment]
My Keon already has the latest update available, there's only been one of them. I don't know of any plans to move Keons off 1.0.1 in the forseeable future...

**Comment by nickdesaulniers** [comment]
@benfrancis Right, they were on an older version of 1.0.1 when you opened this issue.  Then geeksphone released an OTA update, that kept the phone on 1.0.1 but fixed many bugs that had known fixes (including the patch that enabled push to device to work correctly, that @mykmelez referenced). cc @digitarald 
@mykmelez everything should work now, the problem was geeksphones not being up to date on 1.0.1

**Comment by digitarald** [comment]
As the fix didn't land in 1.0.1, you'll need to restart B2G until Keons get 1.1. The fastest way I found is `adb shell "stop b2g && start b2g"`

I agree with @mykmelez that this is a bad experience for a "developer phone", but as it doesn't break the experience for "normal" use I don't see how we could get TEF to revisit the bug.

**Comment by benfrancis** [comment]
@nickdesaulniers The bug is still reproduceable even with the latest update because Keons still run 1.0.1 as @digitarald says.

**Comment by mykmelez** [comment]
> I agree with @mykmelez that this is a bad experience for a "developer phone", but as it doesn't break the experience for "normal" use I don't see how we could get TEF to revisit the bug.

I don't know what the specific criteria are, but generally speaking, I presume that 1.0.1 distributors will want developers to build apps for their devices, and therefore they will consider fixing bugs that impact those developers. In any case, there's no harm in asking.

**Comment by nickdesaulniers** [comment]
@benfrancis , @digitarald , I don't believe that's correct.  I just successful pushed to my peak, running 1.0.1.  @digitarald , we were not able to push without restart initally when the devices weren't receiving OTA updates.  After they did, we could.  @fabricedesre's patch should be in 1.0.1.  Correct me if I'm wrong, but it WFM on a 1.0.1 Peak.

**Comment by nickdesaulniers** [comment]
Ah, trying with a second app, I did have to restart device.  So I guess it's not in 1.0.1.

**Comment by digitarald** [comment]
This only affects the first-time push, updating the app works just fine as the icon is already in place.
https://bugzilla.mozilla.org/show_bug.cgi?id=842725 is wontfix for 1.0.1 (_Tracking Flags_, listed in the lower left corner).

**Comment by rpl** [comment]
after the first-time push, updating the app manifest needs a device restart
to be effective (e.g. changes on the name, orientation or permission
attributes)
